"use client";

import { useRef } from "react";
import { QRCodeCanvas } from "qrcode.react";
import jsPDF from "jspdf";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SheetItem {
  id: string;
  slug: string;
  title: string;
  type: "hold" | "witness";
  status: string;
}

interface Props {
  session: {
    id: string;
    task_description: string;
  };
  items: SheetItem[];
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function ItpQrSheet({ session, items }: Props) {
  const baseUrl = typeof window !== "undefined" ? window.location.origin : "";

  // Canvas refs for each item — used to extract QR code image data
  const canvasRefs = useRef<(HTMLCanvasElement | null)[]>([]);

  function handlePrint() {
    if (items.length === 0) return;

    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 16;
    const qrMm = 52; // QR code square size in mm

    items.forEach((item, idx) => {
      if (idx > 0) doc.addPage();

      const isHold = item.type === "hold";

      // ── Header strip ──────────────────────────────────────────────────────
      doc.setFillColor(248, 250, 252); // slate-50
      doc.rect(0, 0, pageWidth, 14, "F");

      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 116, 139); // slate-500
      const headerText = session.task_description.length > 80
        ? session.task_description.slice(0, 80) + "…"
        : session.task_description;
      doc.text(headerText, margin, 9);

      // ── Type badge ────────────────────────────────────────────────────────
      const badgeY = 20;
      if (isHold) {
        doc.setFillColor(254, 242, 242); // red-50
        doc.setTextColor(185, 28, 28);   // red-700
      } else {
        doc.setFillColor(255, 251, 235); // amber-50
        doc.setTextColor(180, 83, 9);    // amber-700
      }
      doc.roundedRect(margin, badgeY - 5, 26, 8, 2, 2, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text(item.type.toUpperCase(), margin + 13, badgeY, { align: "center" });

      // ── Item title ────────────────────────────────────────────────────────
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(15, 23, 42); // slate-900
      const titleLines = doc.splitTextToSize(item.title, pageWidth - margin * 2) as string[];
      doc.text(titleLines, margin, badgeY + 14);

      const titleBottom = badgeY + 14 + (titleLines.length - 1) * 9;

      // ── QR code ───────────────────────────────────────────────────────────
      const canvas = canvasRefs.current[idx];
      if (canvas) {
        try {
          const qrDataUrl = canvas.toDataURL("image/png");
          const qrX = (pageWidth - qrMm) / 2;
          const qrY = titleBottom + 10;
          doc.addImage(qrDataUrl, "PNG", qrX, qrY, qrMm, qrMm);

          // ── Sign URL below QR ──────────────────────────────────────────────
          const signUrl = `${baseUrl}/itp-sign/${item.slug}`;
          doc.setFontSize(7);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(148, 163, 184); // slate-400
          doc.text(signUrl, pageWidth / 2, qrY + qrMm + 5, { align: "center" });

          // ── Signature line ────────────────────────────────────────────────
          const sigY = qrY + qrMm + 22;
          doc.setDrawColor(203, 213, 225); // slate-300
          doc.setLineWidth(0.4);
          doc.line(margin, sigY, pageWidth - margin, sigY);

          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(100, 116, 139); // slate-500
          doc.text("Signature", margin, sigY + 5);
          doc.text("Name / Date / Company", pageWidth - margin, sigY + 5, { align: "right" });
        } catch {
          // QR canvas not ready — skip image
        }
      }

      // ── Footer ────────────────────────────────────────────────────────────
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(203, 213, 225);
      doc.text("Generated by SiteITP · Buildstate", margin, pageHeight - 8);
      doc.text(`${idx + 1} of ${items.length}`, pageWidth - margin, pageHeight - 8, {
        align: "right",
      });
    });

    const dateStr = new Date().toISOString().slice(0, 10);
    doc.save(`itp-qr-sheet-${session.id.slice(0, 8)}-${dateStr}.pdf`);
  }

  return (
    <>
      {/* Hidden QR canvases — rendered off-screen so refs are populated */}
      <div
        style={{
          position: "fixed",
          top: -9999,
          left: -9999,
          visibility: "hidden",
          pointerEvents: "none",
        }}
        aria-hidden="true"
      >
        {items.map((item, i) => (
          <QRCodeCanvas
            key={item.id}
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            ref={(el: any) => {
              canvasRefs.current[i] = el;
            }}
            value={`${baseUrl}/itp-sign/${item.slug}`}
            size={300}
            level="H"
          />
        ))}
      </div>

      <button
        onClick={handlePrint}
        disabled={items.length === 0}
        className="text-xs font-semibold text-slate-600 border border-slate-200 rounded-xl px-3 py-1.5 hover:bg-slate-50 active:scale-95 transition-transform disabled:opacity-40"
      >
        Print Sign-Off Sheet
      </button>
    </>
  );
}
